name       : dmz-cursor-theme
version    : 0.4.4
release    : 1
source     :
    - http://cdn.debian.net/debian/pool/main/d/dmz-cursor-theme/dmz-cursor-theme_0.4.4.tar.gz : 46af4cf1356df799f9ee94451f05d0bdbb8d82e54bdeae3f32fa107602359981
license    : CC-BY-SA-3.0
component  : desktop.theme
summary    : Style neutral, scalable cursor theme
description: |
    This package contains the DMZ cursor themes, which are derived from  the Industrial theme developed for the Ximian GNOME desktop. Black and white cursors are provided, in scalable formats.
builddeps:
    - xcursorgen
build      : |
    cd DMZ-White/pngs
    ./make.sh
    cd ../../DMZ-Black/pngs
    ./make.sh
install    : |
    install -d $installdir/usr/share/icons/DMZ-Black/cursors/
    install -m644 DMZ-Black/cursor.theme $installdir/usr/share/icons/DMZ-Black/
    install -m644 DMZ-Black/index.theme $installdir/usr/share/icons/DMZ-Black/
    install -m644 DMZ-Black/xcursors/* -t $installdir/usr/share/icons/DMZ-Black/cursors/
    install -d $installdir/usr/share/icons/DMZ-White/cursors/
    install -m644 DMZ-White/cursor.theme $installdir/usr/share/icons/DMZ-White/
    install -m644 DMZ-White/index.theme $installdir/usr/share/icons/DMZ-White/
    install -m644 DMZ-White/xcursors/* -t $installdir/usr/share/icons/DMZ-White/cursors/
