name       : dmz-cursor-theme
version    : 0.4.4
release    : 2
source     :
    - http://cdn.debian.net/debian/pool/main/d/dmz-cursor-theme/dmz-cursor-theme_0.4.4.tar.gz : 46af4cf1356df799f9ee94451f05d0bdbb8d82e54bdeae3f32fa107602359981
license    : CC-BY-SA-3.0
component  : desktop.theme
summary    : Style neutral, scalable cursor theme
description: |
    This package contains the DMZ cursor themes, which are derived from  the Industrial theme developed for the Ximian GNOME desktop. Black and white cursors are provided, in scalable formats.
builddeps:
    - xcursorgen
build      : |
    cd $workdir/DMZ-White/pngs
    ./make.sh
    cd $workdir/DMZ-White/xcursors
    ln -s left_ptr default
    ln -s hand pointer
    ln -s left_ptr_watch progress
    ln -s watch wait
    ln -s xterm text
    ln -s dnd-link alias
    ln -s crossed_circle not-allowed
    ln -s hand1 grab
    ln -s sb_h_double_arrow col-resize
    ln -s sb_v_double_arrow row-resize
    ln -s top_side n-resize
    ln -s right_side e-resize
    ln -s bottom_side s-resize
    ln -s left_side w-resize
    ln -s top_right_corner ne-resize
    ln -s top_left_corner nw-resize
    ln -s bottom_left_corner sw-resize
    ln -s bottom_right_corner se-resize
    ln -s sb_h_double_arrow ew-resize
    ln -s sb_v_double_arrow ns-resize
    ln -s fd_double_arrow nesw-resize
    ln -s bd_double_arrow nwse-resize
    cd $workdir/DMZ-Black/pngs
    ./make.sh
    cd $workdir/DMZ-Black/xcursors
    ln -s left_ptr default
    ln -s hand pointer
    ln -s left_ptr_watch progress
    ln -s watch wait
    ln -s xterm text
    ln -s dnd-link alias
    ln -s crossed_circle not-allowed
    ln -s hand1 grab
    ln -s sb_h_double_arrow col-resize
    ln -s sb_v_double_arrow row-resize
    ln -s top_side n-resize
    ln -s right_side e-resize
    ln -s bottom_side s-resize
    ln -s left_side w-resize
    ln -s top_right_corner ne-resize
    ln -s top_left_corner nw-resize
    ln -s bottom_left_corner sw-resize
    ln -s bottom_right_corner se-resize
    ln -s sb_h_double_arrow ew-resize
    ln -s sb_v_double_arrow ns-resize
    ln -s fd_double_arrow nesw-resize
    ln -s bd_double_arrow nwse-resize
install    : |
    install -d $installdir/usr/share/icons/DMZ-Black/cursors/
    install -m644 DMZ-Black/cursor.theme $installdir/usr/share/icons/DMZ-Black/
    install -m644 DMZ-Black/index.theme $installdir/usr/share/icons/DMZ-Black/
    install -m644 DMZ-Black/xcursors/* -t $installdir/usr/share/icons/DMZ-Black/cursors/
    install -d $installdir/usr/share/icons/DMZ-White/cursors/
    install -m644 DMZ-White/cursor.theme $installdir/usr/share/icons/DMZ-White/
    install -m644 DMZ-White/index.theme $installdir/usr/share/icons/DMZ-White/
    install -m644 DMZ-White/xcursors/* -t $installdir/usr/share/icons/DMZ-White/cursors/
